spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8